FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# установка браузера
RUN playwright install chromium

COPY . .

CMD ["python", "main.py"]